### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by rwb27**
Several changes to run scripts on python3.

NB: changes were also required in picamera/lens_shading and
openflexure_stage so python3 version of these must be installed for this
to work.

### CODE REVIEW

**Comment by rwb27** [comment]
Should probably add some ``from __future__ import print_fuction`` type stuff - in particular, changing ``raw_input`` to ``input`` is unsafe in Python 2, unless we add ``from builtins import input`` at the top.

**Comment by rwb27** [comment]
Thanks to http://python-future.org/compatible_idioms.html

**Comment by rwb27** [comment]
@codeTom if you can add those two imports to the top, I can pull the changes, I've checked everything else and it looks fine.  I'm sad that the lambda-function syntax no longer works, the version before was elegant...

**Comment by codeTom** [comment]
I added the print_function and input imports to keyboard_control, the rest imported print already and input should only be in keyboard_control, but please check in case I missed something.
The lambda change was done automatically with 2to3 as tuple unpacking in function signatures was [removed](https://www.python.org/dev/peps/pep-3113/).

**Comment by codeTom** [comment]
Tested on python2, should be fine now.

**Comment by rwb27** [comment]
thanks for that :)  I'm definitely in the "I like tuple unpacking" camp, but that's probably because I cut my teeth on ML!

**Pull request merged**
